- name: Update apt cache and upgrade packages
  apt:
    update_cache: yes
    upgrade: dist
  become: true

- name: Install common packages
  apt:
    name:
      - git
      - curl
      - vim
      - unzip
    state: present
  become: true

- name: Install Docker CE 
  apt:
    name: docker
    state: present
  become: true

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: true
  become: true

- name: Install OpenJDK 17 
  apt:
    name: openjdk-17-jdk
    state: present
  become: true