- name: Add Jenkins repository key
  ansible.builtin.get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    dest: /usr/share/keyrings/jenkins-keyring.asc
  become: true

- name: Convert key to binary format
  ansible.builtin.command:
    cmd: gpg --dearmor -o /usr/share/keyrings/jenkins-key.gpg /usr/share/keyrings/jenkins-keyring.asc
  args:
    creates: /usr/share/keyrings/jenkins-key.gpg
  become: true

- name: Append Jenkins repository to sources list
  ansible.builtin.apt_repository:
    name: jenkins
    repo: deb [signed-by=/usr/share/keyrings/jenkins-key.gpg] https://pkg.jenkins.io/debian-stable binary/
  become: true

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
  become: true

- name: Ensure Jenkins is started and enabled
  ansible.builtin.service:
    name: jenkins
    state: started
    enabled: true
  become: true

