name: Ansible Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: github-runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH keys and configuration
        env:
          MASTER_SSH_PRIVATE_KEY: ${{ secrets.MASTER_SSH_KEY }}
          WORKER_SSH_PRIVATE_KEY: ${{ secrets.WORKER_SSH_KEY }}
        run: |
          # Create SSH directories
          mkdir -p ~/.ssh
          mkdir -p ./ssh_keys
          
          # Create master SSH key
          echo "${MASTER_SSH_PRIVATE_KEY}" | tr -d '\r' > ./ssh_keys/master_key
          echo "${WORKER_SSH_PRIVATE_KEY}" | tr -d '\r' > ./ssh_keys/worker_key
          chmod 600 ./ssh_keys/master_key
          chmod 600 ./ssh_keys/worker_key
          # Add hosts to known_hosts to avoid verification errors
          ssh-keyscan -H ${{vars.MASTER_IP}} >> ~/.ssh/known_hosts
          ssh-keyscan -H ${{vars.WORKER_IP}} >> ~/.ssh/known_hosts

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible sshpass

      - name: Create inventory file
        run: |
          cat > ./ansible/inventory.ini <<EOF
          [master]
          ${{vars.MASTER_IP}} ansible_user=jenkins_master ansible_ssh_private_key_file=/home/github-runner/actions-runner/_work/hybrid-devops-lab/hybrid-devops-lab/ssh_keys/master_key
          [slaves]
          ${{vars.WORKER_IP}} ansible_user=jenkins_worker ansible_ssh_private_key_file=/home/github-runner/actions-runner/_work/hybrid-devops-lab/hybrid-devops-lab/ssh_keys/worker_key
          EOF

          # Test SSH connection
          echo "Testing SSH connection..."
          ssh -i ./ssh_keys/master_key jenkins_master@${{vars.MASTER_IP}} -I "echo 'SSH connection success'"

      - name: Run Ansible playbook
        working-directory: ./ansible
        run: |
          ansible-playbook -i inventory.ini playbooks/main.yml -vvv
        env:
          ANSIBLE_HOST_KEY_CHECKING: False

      - name: Cleanup SSH keys
        if: always()
        run: |
          rm -f ./ssh_keys/master_key
          rm -f ./ssh_keys/worker_key
          echo "SSH keys cleaned up"