name: Destroy Infra

on:
  workflow_dispatch:

env:
  ENV: ${{ vars.ENV_TYPE }}

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Terraform Destroy
        working-directory: ./Infrastructure
        run: terraform destroy -auto-approve -var-file=./vars/$ENV.env.tfvars
