name: Verify WIF with Azure

on:
  workflow_dispatch:

jobs:
  test-wif:
    runs-on: ubuntu-latest
    permissions:
      id-token: write    # needed for OIDC
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login using WIF
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Show Azure identity
        run: az account show
